---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: jet-tencentcloud-config
  labels:
    app: crossplane-provider-jet-tencentcloud
spec:
  image: simatongming/provider-jet-tencentcloud:0.1.0
  args: ["-d"]
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-provider-jet-tencentcloud
spec:
  package: simatongming/provider-jet-tencentcloud:0.1.0
  controllerConfigRef:
    name: jet-tencentcloud-config
